<?php

namespace Z1px\App\Models;


use Illuminate\Database\Eloquent\Model as BaseModel;
use Z1px\App\Traits\Eloquent\ToColumnsComment;
use Z1px\App\Traits\Eloquent\ToTableComment;

class Model extends BaseModel
{

    /**
     * 是否开启数据库表增删改记录
     * @var bool
     */
    protected $tables_operated = false;
    /**
     * 模型增删改查之前的数据
     * @var array
     */
    protected $before_attributes = [];

    use ToTableComment, ToColumnsComment;


    // 设置模型增删改查之前的数据
    public function setBeforeAttributes($attributes): object
    {
        $this->before_attributes = $attributes;
        return $this;
    }
    public function setBeforeAttribute($key, $value): object
    {
        $this->before_attributes[$key] = $value;
        return $this;
    }

    // 获取模型增删改查之前的数据
    public function getBeforeAttributes()
    {
        return $this->before_attributes;
    }
    // 获取模型增删改查之前的数据
    public function getBeforeAttribute($key)
    {
        return $this->before_attributes[$key] ?? null;
    }

    /**
     * 文件ID转图片地址
     * @param array $data
     * @return string
     */
    public function file_to_image($id = null, array $data = [])
    {
        !is_null($id) || $id = $this->attributes['file_id'];
        if(empty($id)){
            $value = '';
        }else{
            if(app('files_service')->toInfo($id)){
                $data['sn'] = encrypt($id);
                $value = route('files.image', $data);
            }else{
                $value = '';
            }
        }
        unset($id, $data);
        return $value;
    }

    /**
     * 获取适用于请求的验证规则
     *
     * @param $scene 验证场景
     * @return array
     */
    public function rules($scene='update')
    {
        $rules = [];
        switch ($scene){
            case 'info':
            case 'update':
            case 'delete':
            case 'restore':
                $rules['id'] = "required|integer";
                break;
        }
        return $rules;
    }

    /**
     * 获取已定义验证规则的错误消息。
     *
     * @return array
     */
    public function messages($scene=null)
    {
        $messages = [
            'regex' => ':attribute 格式错误',
        ];
        return $messages;
    }

    /**
     * 获取验证错误的自定义属性。
     *
     * @return array
     */
    public function attributes($key=null)
    {
        $attributes = [
            'id' => 'ID',
            'file_id' => '文件ID',
            'type' => '类型',
            'status' => '状态',
            'route_name' => '路由名称',
            'route_action' => '路由方法',
            'url' => '请求地址',
            'method' => '请求类型',
            'ip' => '请求IP',
            'area' => 'IP区域',
            'user_type' => '用户类型',
            'user_id' => '用户ID',
            'admin_id' => '管理员ID',
            'logo' => 'LOGO',
            'start_time' => '开始时间',
            'end_time' => '结束时间',
        ];
        if(is_null($key)){
            return $attributes;
        }else{
            if(!isset($attributes[$key])){
                try{
                    $columns = $this->toColumnsComment();
                    $attributes[$key] = $columns->getColumn($key)->getComment();
                    !empty($attributes[$key]) || $attributes[$key] = $key;
                }catch (\Exception $exception){

                }
            }
            return $attributes[$key] ?? $key;
        }
    }

    /**
     * 查询条件构造
     * @param $data
     * @param array $params
     * @return mixed
     */
    protected function toWhere(object $data, array $params): object
    {
        if(!empty($params)){
            foreach ($params as $key=>$value){
                if(empty($value)) continue;
                switch ($key){
                    case 'title':
                        $data = $data->where($key, 'like', "%{$value}%");
                        break;
                    case 'start_time':
                        $data = $data->whereDate('created_at', '>=', $value);
                        break;
                    case 'end_time':
                        $data = $data->whereDate('created_at', '<=', $value);
                        break;
                    default:
                        if($this->isFillable($key)){
                            if(is_array($value)){
                                $data = $data->whereIn($key, $value);
                            }else{
                                $data = $data->where($key, $value);
                            }
                        }
                }
            }
        }
        return $data;
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($model) {
            if(isset($model->tables_operated) && true === $model->tables_operated) {
                app('tables_operated_service')->toAdd($model, 'create');
            }
        });
        static::updated(function ($model) {
            if(isset($model->tables_operated) && true === $model->tables_operated && $model->wasChanged()) {
                app('tables_operated_service')->toAdd($model, 'update');
            }
        });
        static::deleted(function ($model) {
            if(isset($model->tables_operated) && true === $model->tables_operated) {
                app('tables_operated_service')->toAdd($model, 'delete');
            }
        });
        if(method_exists(static::class, 'restored')){
            static::restored(function ($model) {
                if(isset($model->tables_operated) && true === $model->tables_operated) {
                    app('tables_operated_service')->toAdd($model, 'restore');
                }
            });
        }

    }
}
